### PR TITLE
New year2017

### PR DESCRIPTION
**Pull request by NeuroBinds**
### Description

Up Coming New Years Update #2017
### Reason to modify

Change The API A Bit
### Tests & Reviews

I did not test it yet feel free to change and fix it.

### CODE REVIEW

**Comment by NeuroBinds** [comment]
##DO NOT MERGE IT YET
#Merge when new year 2017

#i basically wanted someone to test it and fix some grammar error or etc
NOTE:: THERE ARE #ERROR

**Comment by HyGlobalHD** [comment]
Thats A Very Messy Code xP by the way my examination should finish 2 week more :-: :+1:

**Comment by HyGlobalHD** [comment]
Oh Yeah By Editing This Plugin PureChat Might Not Support This So I Will Edit The PureChat To Accept This Plugin.

**Comment by NeuroBinds** [comment]
ERROR Found when doing /g create (name)
Please Can someone see this??

**Pull request merged**
