### PR TITLE
Grammar Fixes

### PR DESCRIPTION
**Pull request by Kenner-G**
DESCRIPTION:
Grammar Fixes
WHY MODIFY:
Because grammar is key.
DETAILS:
Thank me. I spent 40+ minutes going through this.

### CODE REVIEW

**Comment by HyGlobalHD** [comment]
I'm Sorry But Please Review Your Fix. I See Something That Are Not  Suppose There.

**Comment by Kenner-G** [comment]
Dude, you do not know English. I am studying English Grammar. First off, its more convenient for a player to do /g instead of /guilds, secondly, you mean a guild not "your guilds", because you can only have one. Consider changing these things, my friend.

**Comment by HyGlobalHD** [comment]
ik but please check every fix, there something that are not suppose there.

**Comment by Kenner-G** [comment]
What is that something, you are being really immature.

**Comment by HyGlobalHD** [comment]
check it for yourself *note: i am immature xP

**Comment by Kenner-G** [comment]
[image: logo]
Listen to music from over 1 million tracks and 250k artists.
Sign Up <http://www.xetonmusic.ga/register>
*Is the button not working? Try visiting our site directly:*
www.xetonmusic.ga/
_______________________________________________
A completely free-service for anyone to stream music.
 Website created, maintained, and hosted by Kenner G.

**Pull request closed without merging**
